var data = [
    {
        "itemSeting":'0',
        "itemGeting":'SesliKitap',
        "itemName": 'Müzikli Kitap Benim Şarkım',
        "itemAuthor": ' Kolektif',
        "interpreter": 'Nevin Avan Özdemir',
        "itemImage": 'bookimg/img1.jpg',
        "itemDescription": 'Bu harika şarkıyla vücudumuzu öğreniyoruz. Çocuğunuz sevimli hayvanlarla birlikte başına, omuzlarına, dizlerine ve ayaklarına dokunup dans ederken hem el ve göz koordinasyonu gelişecek, hem de vücudunu tanıyacak. Çocuğunuza şarkıyı ve dansı bir kez öğrettiğinizde, düğmeye basarak kitabıyla defalarca oynayacaktır.',
        "itemCreateonDate": '2015',
        "itemPublisher": 'İş Bankası Kültür Yayınları',
        "itemNumberofPage": '8',
        "itemLanguage":' Türkçe'
    },
    {
        "itemSeting":'0',
        "itemGeting":'SesliKitap',
        "itemName": 'Eğlenelim-Öğrenelim - Çiftlik Hayvanları',
        "itemAuthor": 'Kolektif',
        "interpreter": '-',
        "itemImage": 'bookimg/img2.jpg',
        "itemDescription": 'Ormanda ve çiftlikte yaşayan hayvanları tanımak ister misin? Ya seslerini duymaya ne dersin?Bu kitaplarda birbirinden sevimi hayvanlar sana sesleniyorlar, seslerini duymanı istiyorlar.Onlara kulak vermeye ne dersin?',
        "itemCreateonDate": '2016',
        "itemPublisher": 'Çiçek Yayıncılık',
        "itemNumberofPage": '12',
        "itemLanguage":'Türkçe'
    },
    {
        "itemSeting":'0',
        "itemGeting":'SesliKitap',
        "itemName": 'Miyav!',
        "itemAuthor": 'Kolektif',
        "interpreter": 'Ali Berktay',
        "itemImage": 'bookimg/img3.jpg',
        "itemDescription": 'Yumuk ile Boncuk’un topları kaçtı! Haydi sen de koş onlarla birlikte, yakala topu! Küçük çocukların basmaya bayılacakları ses düğmesiyle, bu kitap biraz gürültülü, ama çok eğlenceli bir hikâye dünyasının kapılarını aralayacak.',
        "itemCreateonDate": '2017',
        "itemPublisher": 'İş Bankası Kültür Yayınları',
        "itemNumberofPage": '8',
        "itemLanguage":'Türkçe-İngilizce'
    },
    {
        "itemSeting":'0',
        "itemGeting":'EgiticiKart',
        "itemName": 'Minik Adımlar – Renkler',
        "itemAuthor": '-',
        "interpreter": 'MELİKE HENDEK',
        "itemImage": 'bookimg/img4.jpg',
        "itemDescription": 'Bu kitapla bebeğiniz, gerçek fotoğraflar kullanılarak hazırlanmış birbirinden canlı sayfalarda, pek çok yeni kavramla tanışacak, renkleri öğrenecek.',
        "itemCreateonDate": '2017',
        "itemPublisher": 'Pearson',
        "itemNumberofPage": '34',
        "itemLanguage":'Türkçe'
    },
    {
        "itemSeting":'0',
        "itemGeting":'EgiticiKart',
        "itemName": 'Bak Öğren Kartlar - Hayvanlar',
        "itemAuthor": '-',
        "interpreter": '-',
        "itemImage": 'bookimg/img5.jpg',
        "itemDescription": '12 ay ve üzeri bebek ve çocuklarımızın dil ve bilişsel gelişimlerini desteklemek üzere Türkçe ve İngilizce olarak hazırlanmış bir eğitim materyalidir.Kartların bir tarafında sadece resim, diğer tarafında resim ile beraber türkçe ve ingilizce yazılışları mevcuttur.',
        "itemCreateonDate": '2017',
        "itemPublisher": 'Parıltı Yayınları',
        "itemNumberofPage": '32',
        "itemLanguage": 'Türkçe-İngilizce'
    },
    {
        "itemSeting":'0',
        "itemGeting":'EgiticiKart',
        "itemName": 'Bak Öğren Kartlar Renkler-Şekiller',
        "itemAuthor": 'Kolektif',
        "interpreter": '-',
        "itemImage": 'bookimg/img6.jpg',
        "itemDescription": '12 ay ve üzeri bebek ve çocuklarımızın dil ve bilişsel gelişimlerini desteklemek üzere Türkçe ve İngilizce olarak hazırlanmış bir eğitim materyalidir. Kartların bir tarafında sadece resim, diğer tarafında resim ile beraber türkçe ve ingilizce yazılışları mevcuttur.',
        "itemCreateonDate": '2017',
        "itemPublisher": 'Parıltı Yayınları',
        "itemNumberofPage": '11 x 19',
        "itemLanguage":'Türkçe-İngilizce'
    },
    {   
        "itemSeting":'0',
        "itemGeting":'egiticikitap',
        "itemName": "Ece'nin Serüvenleri - Tuvalet Eğitimi",
        "itemAuthor": ' Kolektif',
        "interpreter": '-',
        "itemImage": 'bookimg/img7.jpg',
        "itemDescription": '8 sayfadan oluşan, pırıl pırıl baskılı, selefonlu ve sert kapak ciltlemesi ile serinin bu kitabında, çocuklarımızın, tuvalet ihtiyaçlarını tek başlarına gidermelerinde ve gerekli hijyen alışkanlıklarını kazanabilmelerinde siz ebeveynlere yardımcı olmak hedeflenmiştir. Kitap her biri farklı müzikal altyapıya sahip ve yine Smartteach yayınevi çocuk kulübünce 0-6 yaş grubu çocuklar tarafından seslendirilmiş 3 farklı eğitici ve eğlenceli çocuk şarkısına sahiptir. Şarkılar ve hikâye metinleri çocuklarda olumlu davranış değişiklikleri gerçekleştirmek maksatlı özenle hazırlanmıştır.',
        "itemCreateonDate": '2016',
        "itemPublisher": 'Smarteach',
        "itemNumberofPage": '8',
        "itemLanguage":'Türkçe'
    },
    {
        "itemSeting":'3',
        "itemGeting":'HikaMas',
        "itemName": 'Masal Masal İçinde',
        "itemAuthor": 'Ahmet Ümit',
        "interpreter": '-',
        "itemImage": 'bookimg/img8.jpg',
        "itemDescription": 'Bu kitaptaki masalları annemden dinledim. Annem de küçükken bir masalcıdan dinlemiş. Dedem kızının gönlünü hoş tutmak için bir masalcı tutmaktan çekinmemiş anlaşılan. Annem daha pek çok masal dinlemişti ama hepsini anımsamıyordu. Bana da anlatmış, ben de anımsamıyordum. Aslına bakarsanız bu kitaptaki masalları da çoktan unutmuştum. Yıllar sonra Antep’e baba evine döndüğümde, biraz da rastlantı sonucu annem yeniden anlattı bu masalları.Ahmet Ümit’ten hem küçüklere hem büyüklere masallar! Polisiye roman kurgusuyla; soluksuz takip edilen, hepsi birbirine bağlanan beş masal. Padişah’la beraber Şapkacı’nın, Müezzin’in, Demirci’nin, Kuyumcu’nun, Köradam’ın serüvenlerinin peşinde, adeta Binbir Gece Masalları lezzetiyle…',
        "itemCreateonDate": '2015',
        "itemPublisher": 'Everest Yayınları',
        "itemNumberofPage": '160',
        "itemLanguage":'Türkçe'
    },
    {
        "itemSeting":'3',
        "itemGeting":'HikaMas',
        "itemName": 'Sevimli Hayvanlar Serisi - Küçük Cesur Penguen',
        "itemAuthor": 'Future Co',
        "interpreter": '-',
        "itemImage": 'bookimg/img9.jpg',
        "itemDescription": 'Sevimli Hayvanlar Serisi, Küçük sevimli yavru hayvanlar ile kalplerde ki sevgi duygusunu ortaya çıkaran muhteşem bir koleksiyon. Çocukların hayvanlara karşı sevgi bağını kurmalarına, çevreye ve bütün canlılara karşı daha duyarlı olmalarına yardımcı olacak bu seri ile çocuklarınız hem öğrenecek hemde çok eğlenecek. Her bir kitabın kendine özgü hikâyeleri ve eşsiz çizim ve resimleri ile çocuklarınız eğlenceli vakit geçirecektir.',
        "itemCreateonDate": '2015',
        "itemPublisher": 'Dört Göz Yayınları',
        "itemNumberofPage": '32',
        "itemLanguage":'Türkçe'
    },
    {
        "itemSeting":'3',
        "itemGeting":'HikaMas',
        "itemName": "Ay'a Yolculuk",
        "itemAuthor": 'Jules Verne',
        "interpreter": ' Elif Erdoğdu',
        "itemImage": 'bookimg/img10.jpg',
        "itemDescription": 'Bir maceraperest Ay’a gitmeyi aklına koyar ve hazırlıklara başlar.Jules Verne’in büyülü dünyasıyla tanışmaya hazır mısın?',
        "itemCreateonDate": '2017',
        "itemPublisher": '1001 Çiçek',
        "itemNumberofPage": '24',
        "itemLanguage":'Türkçe'
    },
    {
        "itemSeting":'3',
        "itemGeting":'EtkinKitap',
        "itemName": 'Zihinsel Gelişim Etkinlikleri 1',
        "itemAuthor": 'Berkay Dinç Çakır',
        "interpreter": '-',
        "itemImage": 'bookimg/img11.jpg',
        "itemDescription": 'Zihinsel Gelişim Etkinlikleri Seti, 3 yaş ve üzeri çocukların zihinsel gelişimlerine katkıda bulunmak amacıyla hazırlanmıştır. Bilimsel veriler zekanın geliştirilebilir bir potansiyel olduğunu göstermektedir. Özellikle zenginleştirilmiş bir çevre ve ortam sunulması, çocuğunun zeka potansiyelinin gelişmesi açısında çok önemlidir.Bu kitaplar sayesinde çocuğunuzun zihinsel potansiyelini geliştirmesi için evde zenginleştirilmiş bir ortam oluşturulabilir.Onunla geçirdiğiniz zamanı daha etkin bir şekilde değerlendirebilirsiniz.',
        "itemCreateonDate": '2017',
        "itemPublisher": ' Eolo',
        "itemNumberofPage": '20',
        "itemLanguage":'2017'
    },
    {
        "itemSeting":'3',
        "itemGeting":'EtkinKitap',
        "itemName": 'Kış Zamanı-Muhteşem Çıkartmalar ve Aktiviteler',
        "itemAuthor": ' Kolektif',
        "interpreter": '-',
        "itemImage": 'bookimg/img12.jpg',
        "itemDescription": 'Kış Zamanı-Muhteşem Çıkartmalar ve Aktiviteler',
        "itemCreateonDate": ' 2017',
        "itemPublisher": 'Parıltı Yayınları',
        "itemNumberofPage": '-',
        "itemLanguage":'Türkçe'
    },
    {
        "itemSeting":'3',
        "itemGeting":'egiticikitap',
        "itemName": 'Hareketli Şehir',
        "itemAuthor": 'Rebecca Finn',
        "interpreter": 'Nevin Avan Özdemir',
        "itemImage": 'bookimg/img13.jpg',
        "itemDescription": 'Hareketli Kitaplar çocukların boyut algılarını, el göz koordinasyonlarını ve çevreyle bağlantı kurma yeteneklerini geliştirmek amacıyla hazırlanmıştır. Çocuğunuzun elinden düşürmeyeceği Hareketli Kitaplar serisi hem çok eğlenceli hem de çok dayanıklı',
        "itemCreateonDate": ' 2014',
        "itemPublisher": 'İş Bankası Kültür Yayınları',
        "itemNumberofPage": '12',
        "itemLanguage":'Türkçe'
    },
    {
        "itemSeting":'3',
        "itemGeting":'egiticikitap',
        "itemName": 'Zıplayan Kitaplar- Köpekçik',
        "itemAuthor": 'Kolektif',
        "interpreter": '-',
        "itemImage": 'bookimg/img14.jpg',
        "itemDescription": 'Bastır sonra bırak, köpekçiğin nasıl zıpladığını gör.',
        "itemCreateonDate": '2014',
        "itemPublisher": 'Final Kültür Sanat Yayınları',
        "itemNumberofPage": '4',
        "itemLanguage":'Türkçe'
    },
    {
        "itemSeting":'6',
        "itemGeting":'Hikaye',  
        "itemName": 'Okuldaki İlk Günüm',
        "itemAuthor": 'Kolektif',
        "interpreter": '-',
        "itemImage": 'bookimg/img15.jpg',
        "itemDescription": "Birçok çocuk için okula başlamak ya da yeni dönemde okulların açılması kaygı vericidir. Okuldaki ilk günüm'de, çocuklar eğlendirici bir bakışla okula (yeniden) gitmeye teşvik ediliyor. Kitabın sonunda çocuklar için bazı etkinlikler ve yetişkinler için de bir rehber bulunuyor.",
        "itemCreateonDate": '2011',
        "itemPublisher": 'Tübitak Yayınları',
        "itemNumberofPage": '38',
        "itemLanguage":'Türkçe'
    },
    {
        "itemSeting":'6',
        "itemGeting":'Hikaye',
        "itemName": 'Bir Türlü Yerimde Duramıyorum',
        "itemAuthor": 'Pam Pollack Meg Belviso',
        "interpreter": 'Özden Hanoğlu',
        "itemImage": 'bookimg/img16.jpg',
        "itemDescription": 'Lukas, bir türlü yerinde duramayan bir çocuk. Sınıfta yanıt vermeden önce parmak kaldırmayı ve oyunlarda sırasını beklemeyi hep unutuyor. Kurallara uymayı çok zor buluyor. Oyun kurallarına da uymadığı için diğer çocuklar teneffüslerde onu takımlarında istemiyorlar. Lukas’ın Dehb’si var. Dehb onu aşırı hareketli ve güç odaklanan biri yaptığı için eşyalarını ve odasını düzenli tutamıyor. Anne ve babası Lukas’ı Dehb konusunda uzman bir doktora götürdükten sonra hayatı daha iyiye gitmeye başlıyor. Dikkat Eksikliği Hiperaktivite Bozukluğu ile nasıl baş edileceğini ve onu nasıl kontrol altına alacağını öğreniyor. Ondan sonra her şey Lukas için daha kolay ve eğlenceli hale geliyor.',
        "itemCreateonDate": '2011',
        "itemPublisher": 'Tübitak Yayınları',
        "itemNumberofPage": '33',
        "itemLanguage":'Türkçe'
    },
    {
        "itemSeting":'6',
        "itemGeting":'Hikaye',
        "itemName": "1, 2, 3 Hooop! Mısır'da - Horus'un Gözü",
        "itemAuthor": 'Cristina Falcon Maldonado',
        "interpreter": '-',
        "itemImage": 'bookimg/img17.jpg',
        "itemDescription": "Genç Martin'in bir gezgin ve kâşif olan büyükbabası, gizli deposunun anahtarını artık Martin'e vermiştir. Büyükbaba gizli deposunda çok değerli fotoğraf albümünü ve Martin'i uzak yerlere götürecek büyülü kolyeyi saklamaktadır. 1, 2, 3 Hooop! Mısır'da Martin'in macerası Mısır'ın Büyük Sfenks'ini ziyaret ettiği sırada, yakalandığı bir kum fırtınası ile başlıyor. Eski Mısır Firavunları hakkına birçok şey öğreniyor. Bir zamanlar eski Mısır'ın başkenti olan Luksor'da bulunan Krallar Vadisi'ne ve antik tapınaklar kenti Karnak'a yolculuk yapıyor. Ayrıca Ramazan ayı, Arap yiyecekleri ve Mısır tarihine ilişkin bilgiler edindiği modern Kahire kentini de gezecek zaman buluyor.",
        "itemCreateonDate": '2011',
        "itemPublisher": 'Tübitak Yayınları',
        "itemNumberofPage": '30',
        "itemLanguage":'Türkçe'
    },
    {
        "itemSeting":'6',
        "itemGeting":'Masal',
        "itemName": 'R Endişeyle Seslendi - Virgül Nerdesin?',
        "itemAuthor": 'Alp Gökalp',
        "interpreter": '',
        "itemImage": 'bookimg/img18.jpg',
        "itemDescription": 'Noktalama işaretleri isyan çıkarıyor! Uzun zaman önce insanlar yazmaları gerektiğini keşfettiler, fakat nasıl yazı yazılacağını bilmiyorlardı. Tam o sırada, Alfabe Bulutu adındaki, dünyaya en yakın bulutta yaşamlarını sürdüren harfler, yazmayı öğretmek için insanlarla iletişime geçtiler. İşte Alfabe Bulutu serisi, burada yaşayan bulut sakinlerinin hikâyeleri…Noktalama işaretleri asırlardır harflerle birlikte uyum içinde yaşıyorlardı. Fakat bir gün hayatı sorgulamaya başlarlar. Harflerin evcil hayvanı olarak yaşamak onlara yetmez artık. Güçlerini birleştirerek başkaldıramaya karar verirler. Özgürlük ve bağımsızlık konuları kadar birlikte yaşamanın ve uzlaşmanın önemini de vurguluyor yazar bu kitapta. Serinin her kitabı farklı bir çizer tarafından yorumlandı; yazarın eğlenceli anlatımı, zengin görsellerle sunulmaktadır.',
        "itemCreateonDate": '2016',
        "itemPublisher": 'Redhouse Kidz Yayınları',
        "itemNumberofPage": '68',
        "itemLanguage":'Türkçe'
    },
    {
        "itemSeting":'6',
        "itemGeting":'Masal',
        "itemName": 'Ya Başkası Olsaydım?',
        "itemAuthor": 'Alp Gökalp',
        "interpreter": '-',
        "itemImage": 'bookimg/img19.jpg',
        "itemDescription": "Uzun zaman önce insanlar yazmaları gerektiğini keşfettiler, fakat nasıl yazı yazılacağını bilmiyorlardı. Tam o sırada, Alfabe Bulutu adındaki, dünyaya en yakın bulutta yaşamlarını sürdüren harfler, yazmayı öğretmek için insanlarla iletişime geçtiler. İşte Alfabe Bulutu serisi, burada yaşayan bulut sakinlerinin hikâyeleri…Günlerdir sebebini bilmediği bir boşluk hissi vardır S'nin içinde. Hayattan eskisi gibi zevk almamakta, kendisine eskisi gibi özen göstermemektedir. Yaşama sevincini kaybetmek üzere olan S, Alfabe Bulutu'nun saygın harflerinden A'nın büyük malikânesine bakarken, birden A'nın görkemli hayatını hayal etmeye başlar…Böylece sorununa çözümü bulmuş bir şekilde mırıldanır: Ya başkası olsaydım? Çocuklara sahip olduklarının kıymetini bilme, elindekilerle mutlu olma gibi olguları tanıtan bu kitap, Alfabe Bulutu serisinin ilk kitabıdır. Serinin her kitabı farklı bir çizer tarafından yorumlanmış; yazarın eğlenceli anlatımı, zengin görsellerle sunulmaktadır.",
        "itemCreateonDate": '2016',
        "itemPublisher": 'Redhouse Kidz Yayınları',
        "itemNumberofPage": '68',
        "itemLanguage":'Türkçe'
    },
    {
        "itemSeting":'6',
        "itemGeting":'Masal',
        "itemName": 'İmparator Tırtılı',
        "itemAuthor": 'Nevin Demirel',
        "interpreter": '-',
        "itemImage": 'bookimg/img20.jpg',
        "itemDescription": 'Canlılar doğada ekolojik dengenin bir parçası olmuş; her bir canlı doğal dengenin korunmasına katkıda bulunmuştur. Bu kitapta yazar, Hindistan’da yaşayan İmparator Tırtıllarının doğada verdiği yaşam mücadelesini ve sonrasında bu tırtılların ördükleri kozaların içinden, çeşitli renklerde birer kelebeğe dönüşerek doğadaki yerlerin almalarını anlatmaktadır.',
        "itemCreateonDate": '2011',
        "itemPublisher": 'Tübitak Yayınları',
        "itemNumberofPage": '30',
        "itemLanguage":'Türkçe'
    },
    {
        "itemSeting":'8',
        "itemGeting":'Roman',
        "itemName": 'Şeker Portakalı',
        "itemAuthor": 'Jose Mauro De Vasconcelos',
        "interpreter": 'Aydın Emeç',
        "itemImage": 'bookimg/img21.jpg',
        "itemDescription": "Çok yoksul bir ailenin oğlu olarak dünyaya gelen, dokuz yaşında yüzme öğrenirken bir gün yüzme şampiyonu olmanın hayalini kuran Vasconcelos'un çocukluğundan derin izler taşıyan Şeker Portakalı, yaşamın beklenmedik değişimleri karşısında büyük sarsıntılar yaşayan küçük Zeze'nin başından geçenleri anlatır. Vasconcelos, tam on iki günde yazdığı bu romanı 'yirmi yıldan fazla bir zaman yüreğinde taşıdığını' söyler.Aydın Emeç'in, güzel Türkçesiyle dilimize armağan ettiği Şeker Portakalı'nın başkahramanı Zeze'nin büyüdükçe yaşadığı serüvenleri, yazarın Güneşi Uyandıralım ve Delifişek adlı romanlarında izleyebilirsiniz.",
        "itemCreateonDate": '2016',
        "itemPublisher": 'Can Çocuk Yayınları',
        "itemNumberofPage": '200',
        "itemLanguage":'Türkçe'
    },
    {
        "itemSeting":'8',
        "itemGeting":'Roman',
        "itemName": 'Robotum Zeytin',
        "itemAuthor": 'Buket Çetin',
        "interpreter": '-',
        "itemImage": 'bookimg/img22.jpg',
        "itemDescription": 'Uğur, kardeşi Ayşe ile yeni bir oyun keşfeder. Bu, “bom bom” oyunudur. Keşfettikleri bu oyunun ardından yaşamlarında pek çok şey değişir. En garibi, Uğur, Zeytin isimli bir robotla tanışır. Zeytin zamanla Uğur’un en yakın dostu olur ve onun yaşamındaki her şeye tanıklık eder. Birlikte oyunlar oynar, pek çok maceraya katılırlar… Önce, bir şehirden başka bir şehre göç etmek zorunda kalırlar. Birlikte hayali bir dünyada, Minerva adlı bir tanrıçayla tanışırlar. Minerva’nın ise onlar için büyük sürprizleri vardır. Acaba Uğur’un bu hayali dünyayı gerçeklerden ayırt etmesi mümkün olacak mıdır?',
        "itemCreateonDate": '2017',
        "itemPublisher": 'Altın Kitaplar',
        "itemNumberofPage": '120',
        "itemLanguage":'Türkçe'
    },
    {
        "itemSeting":'8',
        "itemGeting":'CizgiDizi',
        "itemName": 'Superman ile Tanışıyorum',
        "itemAuthor": 'Kolektif',
        "interpreter": '-',
        "itemImage": 'bookimg/img23.jpg',
        "itemDescription": 'Geleceğin süper kahramanları çelik adam’la tanışıyor! Süperman, x-ışını görüşüyle duvarların arkasında neler döndüğünü görebilir ve pelerini onun havada bir kuş gibi uçmasını sağlar. Clark kent’in ya da dc süper kahramanlar dünyasındaki adıyla süperman’in hızlı hayatına göz atmaya ne dersiniz?',
        "itemCreateonDate": '2017',
        "itemPublisher": 'Artemis Yayınları',
        "itemNumberofPage": '24',
        "itemLanguage":'Türkçe'
    },
    {
        "itemSeting":'8',
        "itemGeting":'CizgiDizi',
        "itemName": 'Winx Club Sihirli Kütüphane',
        "itemAuthor": 'Iginio Straffi',
        "interpreter": '-',
        "itemImage": 'bookimg/img24.jpg',
        "itemDescription": "Sen de sihre inanıyor ve daha güzel bir dünyanın hayalini mi kuruyorsun? Öyleyse Winx Perileri'nin en güzel hikâyeleri tam sana göre! Peri Eldora'nın sihirli kütüphanesi Winx Perileri için tam bir hazine. Periler raflardaki eski büyüler ve sihirli sözcükler arasında dolaşmak için son derece sabırsız. Cadı Selina'nın gelişiyle ise ortalık biraz karışıyor. Bakalım Selina'nın sebep olduğu bu karmaşadan periler nasıl kurtulacak?",
        "itemCreateonDate": '2016',
        "itemPublisher": 'Artemis Yayınları',
        "itemNumberofPage": '60',
        "itemLanguage":'Türkçe'
    },
    {
        "itemSeting":'8',
        "itemGeting":'Hikaye',
        "itemName": 'Kanatlı Denizatı',
        "itemAuthor": 'Özgür Özgülgün',
        "interpreter": '-',
        "itemImage": 'bookimg/img25.jpg',
        "itemDescription": "Davetsiz Dedektifler, çocuklar için kaleme alınmış, polisiye tadında dedektif öykülerinden oluşuyor. Her öykü merak, akıl yürütme, gözlem gibi temel yaşamsal ögeleri öne çıkaran heyecanlı olaylarla dolu... Öykülerin kahramanları olan Can ve Şevval, sizler gibi meraklı çocuklar. Onlarla kimi zaman Kahire Müzesinin karanlık koridorlarında, kimi zaman Ayasofya'nın uçsuz bucaksız dehlizlerinde nefes nefese bir serüvene hazırsanız, haydi öyleyse! Oyuncu Özgür Özgülgün çocuklarla buluşmaya şimdi de satır aralarında devam ediyor.",
        "itemCreateonDate": '2017',
        "itemPublisher": 'Altın Kitaplar',
        "itemNumberofPage": '48',
        "itemLanguage":'Türkçe'
    },
    {
        "itemSeting":'8',
        "itemGeting":'Hikaye',
        "itemName": 'İlk Okuma Kitaplarım – Penguenler',
        "itemAuthor": 'Susanna Davidson',
        "interpreter": '-',
        "itemImage": 'bookimg/img26.jpg',
        "itemDescription": 'İş Kültür Yayınları İlk Okuma Kitaplarım serisi okumayı öğrenme sürecindeki çocuklara yardımcı kitaplar olarak hazırlanmıştır. Uzman eğitimciler tarafından hazırlanan bu kitaplarda çocukların ilgisini çekecek hikâyeler, resimler, rahat okumaya uygun yazı biçimleri, sonuç çıkarma yetilerini geliştirecek bulmacalar yer alır. Kitaplar başlangıç seviyesinden rahat okuyabilme seviyesine kadar çocukların okumayı öğrenirken geçtiği dört seviyede gruplanmıştır.',
        "itemCreateonDate": '2009',
        "itemPublisher": 'İş Bankası Kültür Yayınları',
        "itemNumberofPage": '54',
        "itemLanguage":'Türkçe'
    },
    {
        "itemSeting":'8',
        "itemGeting":'CocukBilKur',
        "itemName": 'Hayat Oyunu',
        "itemAuthor": 'James Dashner',
        "interpreter": 'Gizem Yeşildal',
        "itemImage": 'bookimg/img27.jpg',
        "itemDescription": 'SanalAğ insan zihni ve bedenine müthiş bir oyun deneyimi yaşatacak en yeni teknoloji ile son derece sofistike oyunları bir araya getirmiştir. Ancak sanal dünyayı gerçeğinden ayıran çizgi bulanıklaşmıştır. Michael artık Uyku’ya her daldığında hayatını riske atmaktadır. SanalAğ ölümcül bir dünya haline gelmiş, Kaine’in planı Ölümsüzlük İlkesi neredeyse gerçekleşmiştir. Başarıya ulaşırsa dünya çapında bir siber egemenlik hüküm sürecektir. Bu canavarı ait olduğu yere ancak Michael ile arkadaşları kapayabilir…',
        "itemCreateonDate": '2017',
        "itemPublisher": 'Pegasus',
        "itemNumberofPage": '320',
        "itemLanguage":'İngilizce-Türkçe'
    },
    {
        "itemSeting":'8',
        "itemGeting":'Felsefe',
        "itemName": 'İyiliğin ve Mutluluğun Yollarını Arıyoruz',
        "itemAuthor": 'Özlem Yarkın',
        "interpreter": '-',
        "itemImage": 'bookimg/img28.jpg',
        "itemDescription": "İki bin beş yüz yıl önce insanlık, Antik Yunan'da evreni anlamaya çalışılırken Hindistan'da iyiliğin ve mutluluğun yollarını arıyordu.",
        "itemCreateonDate": '2016',
        "itemPublisher": 'Öteki Yayınevi',
        "itemNumberofPage": '63',
        "itemLanguage":'Türkçe'
    },
    {
        "itemSeting":'8',
        "itemGeting":'Fantastik',
        "itemName": 'Ejderha Avcıları Okulu 19 - Esrarengiz Dev',
        "itemAuthor": 'Kate Mcmullan',
        "interpreter": '-',
        "itemImage": 'bookimg/img29.jpg',
        "itemDescription": "Okulun yanındaki Kara Orman’da garip şeyler oluyordu. Wiglaf’ın sevgili ejderhası Kurtçuk büyük bir tehlike ile karşı karşıyaydı ve çocuklar, tüm çabalarına rağmen onun kaçırılmasına engel olamadılar. Şimdi DEV gibi bir sorun yaşıyorlardı. Sizce Wiglaf ve arkadaşları, Kurtçuk’u kilitli kafesten çıkarıp devlerin elinden kurtarabilecekler mi?",
        "itemCreateonDate": '2017',
        "itemPublisher": 'Beyaz Balina Yayınları',
        "itemNumberofPage": '150',
        "itemLanguage":'Türkçe'
    },
    {
        "itemSeting":'8',
        "itemGeting":'Siir',
        "itemName": 'Şermin',
        "itemAuthor": 'Tevfik Fikret',
        "interpreter": '-',
        "itemImage": 'bookimg/img30.jpg',
        "itemDescription": "Şermin, yaklaşık yüz yıl önce yayımlanmış bir kitap. Tevfik Fikret'in son eseri. Aradan geçen yıllara ve anlayış değişikliklerine karşın, neredeyse bugün yazılmış gibi şiirler. İlk yayımlanışından bugüne hemen her kuşakta iz bırakmış, şiir ezberlemenin ezbercilik sayılmadığı yıllarda yer ettiği belleklerde yaşamaya devam etmiş. Eskimiş ama lezzeti de bu özelliğinde gizli güzel çocuk şiirleri... ",
        "itemCreateonDate": '2015',
        "itemPublisher": 'Yapı Kredi Yayınları',
        "itemNumberofPage": '112',
        "itemLanguage":'Türkçe'
    },
    {
        "itemSeting":'12',
        "itemGeting":'Roman',
        "itemName": 'Alayına New York',
        "itemAuthor": 'Emine Can',
        "interpreter": '-',
        "itemImage": 'bookimg/img31.jpg',
        "itemDescription": "Tam huzura erdiğinizi düşündüğünüz bir an gelir ve en yakın arkadaşınız bir şey yaparak o anı mahveder ya hani... İşte benim en yakın arkadaşım -kod adı Küfürbaz Haydo,  gerçek ismi Aygül’dür- soylu bir aşiretin biricik oğluyla kaçmıştı ve ardında hiçbir iz bırakmadan kayıplara karışmıştı. Bana ve diğerlerine ise ne mi bırakmıştı? Durdurulması gereken bir düğün, kaçırılması gereken bir gelin ve paçayı kurtarmamız gereken belalı bir olay!  Anlayacağınız macera o bitti diyene kadar bitmiyor,  kaldığı yerden devam ediyordu!",
        "itemCreateonDate": '2017',
        "itemPublisher": 'Epsilon Yayınevi',
        "itemNumberofPage": '288',
        "itemLanguage":'Türkçe'
    },
    {
        "itemSeting":'12',
        "itemGeting":'Hikaye',
        "itemName": 'Alfa Kuzey Bölge - Metal Böcek',
        "itemAuthor": 'Mustafa Hakkı Kurt',
        "interpreter": '-',
        "itemImage": 'bookimg/img32.jpg',
        "itemDescription": '"Süper Kahraman Aranıyor!" ile başlayan "Alfa Kuzey Bölge" serisinin 2. kitabı "Metal Böcek" ile macera kaldığı yerden devam ediyor.Artık Alfa Kuzey Bölge nin 33 numaralı üyesi olan Batuhan ı gitgide daha zor görevler bekliyor. Üstelik bu kez işin içine dünya dışından ziyaretçiler de girecek... Acaba Batuhan üstlendiği görevlerin üstesinden gelebilecek ve bunu yaparken kimliğini de gizli tutmayı başarabilecek mi?',
        "itemCreateonDate": '2014',
        "itemPublisher": 'Mavi Bulut Yayıncılık',
        "itemNumberofPage": '208',
        "itemLanguage":'Türkçe'
    },
    {
        "itemSeting":'12',
        "itemGeting":'Siir',
        "itemName": 'Ay Kaç Yaşında',
        "itemAuthor": 'Mavisel Yener, Aytül Akal',
        "interpreter": '-',
        "itemImage": 'bookimg/img33.jpg',
        "itemDescription": "Mavisel Yener ve Aytül Akal'ın karışık şiirleşmelerini topladıkları Kuş Uçtu Şiir Kaldı ve Şiirimi Kedi Kaptı kitaplarından sonra yayımlanan şiir kitabımız Ay Kaç Yaşında.",
        "itemCreateonDate": '2006',
        "itemPublisher": 'Uçanbalık Yayıncılık',
        "itemNumberofPage": '64',
        "itemLanguage":'Türkçe'
    },
    {
        "itemSeting":'12',
        "itemGeting":'Biyografi',
        "itemName": 'Suyu Arayan Adam',
        "itemAuthor": 'Şevket Süreyya Aydemir',
        "interpreter": '-',
        "itemImage": 'bookimg/img34.jpg',
        "itemDescription": "Bu kitap, ilkokul öğretmeni olarak yetişmek üzereyken, Birinci Dünya Harbinde savaşa katılan ve sonra Büyük Turan'ı kurmak yolunda Kafkas, Hazer ülkelerine koşan bir Türk gencinin hikayesidir. Şimdi bu yeni baskısını sunduğumuz bu eserin yazarı Şevket Süreyya Aydemir; Rusya'da, Sovyet inkılabı cereyan ederken, aralarında Enver Paşanın da bulunduğu önemli şahsiyetlerle karşılaşmıştı. Yazar, Rusya'da tahsilini tamamlayarak memleketine dönmüş, hayatın acı ve tatlı çeşitli olaylarını yaşamıştır. Sonra devletin yüksek hizmet mevkilerinde çalışan Şevket Süreyya Aydemir'in hayat hikayesi, Orta Anadolu bozkırında bir toprağa yönelişle biter.Suyu Arayan Adamda yüzyılımızın, Avrupa'dan Çin'e ve Himalayalara kadar uzanan çeşitli problemlerini de bulacaksınız.",
        "itemCreateonDate": '2016',
        "itemPublisher": 'Remzi Kitabevi',
        "itemNumberofPage": '488',
        "itemLanguage":'Türkçe'
    },
    {
        "itemSeting":'12',
        "itemGeting":'Fanrastik',
        "itemName": 'Ötedünya 1 - Kahramansız Topraklar',
        "itemAuthor": 'Brandon Mull',
        "interpreter": 'Gökhan Yıldırım',
        "itemImage": 'bookimg/img35.jpg',
        "itemDescription": "Bu kelimeleri okuyarak, zorba efendimi tahtından indirmenin tek yolu olan anahtar sözcük'ü bir araya getirmeye gönüllü oldun. Atik davran. Artık sahip olduğun bilgi, tez zamanda idam edilmen için seni hedef gösteriyor. İlk hece 'a'. Brandon Mull kelimelerle bir büyücü gibi oynuyor. Ötedünya'da yıllardır okuduğum en orijinal fantastik âlemlerden birini yaratmış. -Rick Riordan, Percy Jackson & Olimposlular serisinin yazarı-",
        "itemCreateonDate": '2015',
        "itemPublisher": 'Pegasus',
        "itemNumberofPage": '560',
        "itemLanguage":'Türkçe'
    },
    {
        "itemSeting":'12',
        "itemGeting":'Felsefe',
        "itemName": 'Toprağa Yerleştik',
        "itemAuthor": 'Özlem Yarkın',
        "interpreter": '-',
        "itemImage": 'bookimg/img36.jpg',
        "itemDescription": "On bin yıl önce Konya'da kurulan ilk köy, Çatalhöyük... İnsanlar artık göçebe yaşamıyorlar. Toprağa yerleşip üretim yapmaya başladılar. Bundan sonra işler biraz daha karmaşıklaşıyor. Küçük filozoflarımızı takip edelim...",
        "itemCreateonDate": '2016',
        "itemPublisher": 'Öteki Yayınevi',
        "itemNumberofPage": '63',
        "itemLanguage":'Türkçe'
    },
    {
        "itemSeting":'8',
        "itemGeting":'Roman',
        "itemName": 'Yandım Ali',
        "itemAuthor": 'Fakir Baykurt',
        "interpreter": '-',
        "itemImage": 'bookimg/img37.jpg',
        "itemDescription": "Tahir, sıcak yaz günlerinde babasının uzak tepedeki bostanında tek başına bekçilik yapmaktadır. Sulanmayan toprakta da kavun, karpuz yetişebileceğini köylüye kanıtlamak isteyen babasının hayalleri küçük Tahir'e direnme gücü vermektedir. Günün birinde bostana, askerden yeni dönmüş yiğit çoban Yandım Ali gelir. Köyün zengin kızına sevdalı Yandım Ali'yle Tahir'in arkadaşlığı ilginç bir alışverişle gelişir…",
        "itemCreateonDate": '2011',
        "itemPublisher": 'Günışığı Kitaplığı',
        "itemNumberofPage": '152',
        "itemLanguage":'Türkçe'
    },
    {
        "itemSeting":'6',
        "itemGeting":'HikaMas',
        "itemName": 'Küçük Kara Balık',
        "itemAuthor": 'Samed Behrengi',
        "interpreter": 'Haşim Hüsrevşahi',
        "itemImage": 'bookimg/img38.jpg',
        "itemDescription": "Kış ortasında bir akşam vaktiydi. Denizin en derin yerinde, yaşlı mı yaşlı bir balık nine sayıları on iki bini bulan çocuklarıyla torunlarını çevresine toplamış, onlara bir masal anlatıyordu...",
        "itemCreateonDate": '2016',
        "itemPublisher": 'Can Çocuk Yayınları',
        "itemNumberofPage": '55',
        "itemLanguage":'Türkçe'
    }

    
    
    
];